spring.application.name=gestaodechamados
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:file:./data/chamados;AUTO_SERVER=TRUE
spring.jpa.hibernate.ddl-auto=update